import axios from 'axios'
import { Request, Response } from 'express'

const holder: any = {
  'Abia State': [
    'Aba North',
    'Aba South',
    'Arochukwu',
    'Bende',
    'Ikwuano',
    'Isiala Ngwa North',
    'Isiala Ngwa South',
    'Isuikwuato',
    'Obi Ngwa',
    'Ohafia',
    'Osisioma',
    'Ugwunagbo',
    'Ukwa East',
    'Ukwa West',
    'Umuahia North',
    'muahia South',
    'Umu Nneochi',
  ],
  'Adamawa State': [
    'Demsa',
    'Fufure',
    'Ganye',
    'Gayuk',
    'Gombi',
    'Grie',
    'Hong',
    'Jada',
    'Larmurde',
    'Madagali',
    'Maiha',
    'Mayo Belwa',
    'Michika',
    'Mubi North',
    'Mubi South',
    'Numan',
    'Shelleng',
    'Song',
    'Toungo',
    'Yola North',
    'Yola South',
  ],
  'Akwa Ibom State': [
    'Abak',
    'Eastern Obolo',
    'Eket',
    'Esit Eket',
    'Essien Udim',
    'Etim Ekpo',
    'Etinan',
    'Ibeno',
    'Ibesikpo Asutan',
    'Ibiono-Ibom',
    'Ika',
    'Ikono',
    'Ikot Abasi',
    'Ikot Ekpene',
    'Ini',
    'Itu',
    'Mbo',
    'Mkpat-Enin',
    'Nsit-Atai',
    'Nsit-Ibom',
    'Nsit-Ubium',
    'Obot Akara',
    'Okobo',
    'Onna',
    'Oron',
    'Oruk Anam',
    'Udung-Uko',
    'Ukanafun',
    'Uruan',
    'Urue-Offong Oruko',
    'Uyo',
  ],
  'Anambra State': [
    'Aguata',
    'Anambra East',
    'Anambra West',
    'Anaocha',
    'Awka North',
    'Awka South',
    'Ayamelum',
    'Dunukofia',
    'Ekwusigo',
    'Idemili North',
    'Idemili South',
    'Ihiala',
    'Njikoka',
    'Nnewi North',
    'Nnewi South',
    'Ogbaru',
    'Onitsha North',
    'Onitsha South',
    'Orumba North',
    'Orumba South',
    'Oyi',
  ],
  'Bauchi State': [
    'Alkaleri',
    'Bauchi',
    'Bogoro',
    'Damban',
    'Darazo',
    'Dass',
    'Gamawa',
    'Ganjuwa',
    'Giade',
    'Itas-Gadau',
    'Jama are',
    'Katagum',
    'Kirfi',
    'Misau',
    'Ningi',
    'Shira',
    'Tafawa Balewa',
    ' Toro',
    ' Warji',
    ' Zaki',
  ],

  'Bayelsa State': [
    'Brass',
    'Ekeremor',
    'Kolokuma Opokuma',
    'Nembe',
    'Ogbia',
    'Sagbama',
    'Southern Ijaw',
    'Yenagoa',
  ],
  'Benue State': [
    'Agatu',
    'Apa',
    'Ado',
    'Buruku',
    'Gboko',
    'Guma',
    'Gwer East',
    'Gwer West',
    'Katsina-Ala',
    'Konshisha',
    'Kwande',
    'Logo',
    'Makurdi',
    'Obi',
    'Ogbadibo',
    'Ohimini',
    'Oju',
    'Okpokwu',
    'Oturkpo',
    'Tarka',
    'Ukum',
    'Ushongo',
    'Vandeikya',
  ],
  'Borno State': [
    'Abadam',
    'Askira-Uba',
    'Bama',
    'Bayo',
    'Biu',
    'Chibok',
    'Damboa',
    'Dikwa',
    'Gubio',
    'Guzamala',
    'Gwoza',
    'Hawul',
    'Jere',
    'Kaga',
    'Kala-Balge',
    'Konduga',
    'Kukawa',
    'Kwaya Kusar',
    'Mafa',
    'Magumeri',
    'Maiduguri',
    'Marte',
    'Mobbar',
    'Monguno',
    'Ngala',
    'Nganzai',
    'Shani',
  ],
  'Cross River State': [
    'Abi',
    'Akamkpa',
    'Akpabuyo',
    'Bakassi',
    'Bekwarra',
    'Biase',
    'Boki',
    'Calabar Municipal',
    'Calabar South',
    'Etung',
    'Ikom',
    'Obanliku',
    'Obubra',
    'Obudu',
    'Odukpani',
    'Ogoja',
    'Yakuur',
    'Yala',
  ],

  'Delta State': [
    'Aniocha North',
    'Aniocha South',
    'Bomadi',
    'Burutu',
    'Ethiope East',
    'Ethiope West',
    'Ika North East',
    'Ika South',
    'Isoko North',
    'Isoko South',
    'Ndokwa East',
    'Ndokwa West',
    'Okpe',
    'Oshimili North',
    'Oshimili South',
    'Patani',
    'Sapele',
    'Udu',
    'Ughelli North',
    'Ughelli South',
    'Ukwuani',
    'Uvwie',
    'Warri North',
    'Warri South',
    'Warri South West',
  ],

  'Ebonyi State': [
    'Abakaliki',
    'Afikpo North',
    'Afikpo South',
    'Ebonyi',
    'Ezza North',
    'Ezza South',
    'Ikwo',
    'Ishielu',
    'Ivo',
    'Izzi',
    'Ohaozara',
    'Ohaukwu',
    'Onicha',
  ],
  'Edo State': [
    'Akoko-Edo',
    'Egor',
    'Esan Central',
    'Esan North-East',
    'Esan South-East',
    'Esan West',
    'Etsako Central',
    'Etsako East',
    'Etsako West',
    'Igueben',
    'Ikpoba Okha',
    'Orhionmwon',
    'Oredo',
    'Ovia North-East',
    'Ovia South-West',
    'Owan East',
    'Owan West',
    'Uhunmwonde',
  ],

  'Ekiti State': [
    'Ado Ekiti',
    'Efon',
    'Ekiti East',
    'Ekiti South-West',
    'Ekiti West',
    'Emure',
    'Gbonyin',
    'Ido Osi',
    'Ijero',
    'Ikere',
    'Ikole',
    'Ilejemeje',
    'Irepodun-Ifelodun',
    'Ise-Orun',
    'Moba',
    'Oye',
  ],
  Rivers: [
    'Abua–Odual',
    'Ahoada East',
    'Ahoada West',
    'Akuku-Toru',
    'Andoni',
    'Asari-Toru',
    'Bonny',
    'Degema',
    'Emohua',
    'Eleme',
    'Etche',
    'Gokana',
    'Ikwerre',
    'Khana',
    'Obio-Akpor',
    'Ogba–Egbema–Ndoni',
    'Ogu-Bolo',
    'Okrika',
    'Omuma',
    'Opobo–Nkoro',
    'Oyigbo',
    'Port Harcourt',
    'Tai',
  ],
  'Enugu State': [
    'Aninri',
    'Awgu',
    'Enugu East',
    'Enugu North',
    'Enugu South',
    'Ezeagu',
    'Igbo Etiti',
    'Igbo Eze North',
    'Igbo Eze South',
    'Isi Uzo',
    'Nkanu East',
    'Nkanu West',
    'Nsukka',
    'Oji River',
    'Udenu',
    'Udi',
    'Uzo Uwani',
  ],
  'Federal Capital Territory': [
    'Abaji',
    'Bwari',
    'Gwagwalada',
    'Kuje',
    'Kwali',
    'Municipal Area Council',
  ],
  'Gombe State': [
    'Akko',
    'Balanga',
    'Billiri',
    'Dukku',
    'Funakaye',
    'Gombe',
    'Kaltungo',
    'Kwami',
    'Nafada',
    'Shongom',
    'Yamaltu-Deba',
  ],
  'Imo State': [
    'Aboh Mbaise',
    'Ahiazu Mbaise',
    'Ehime Mbano',
    'Ezinihitte',
    'Ideato North',
    'Ideato South',
    'Ihitte-Uboma',
    'Ikeduru',
    'Isiala Mbano',
    'Isu',
    'Mbaitoli',
    'Ngor Okpala',
    'Njaba',
    'Nkwerre',
    'Nwangele',
    'Obowo',
    'Oguta',
    'Ohaji-Egbema',
    'Okigwe',
    'Orlu',
    'Orsu',
    'Oru East',
    'Oru West',
    'Owerri Municipal',
    'Owerri North',
    'Owerri West',
    'Unuimo',
  ],
  'Jigawa State': [
    'Auyo',
    'Babura',
    'Biriniwa',
    'Birnin Kudu',
    'Buji',
    'Dutse',
    'Gagarawa',
    'Garki',
    'Gumel',
    'Guri',
    'Gwaram',
    'Gwiwa',
    'Hadejia',
    'Jahun',
    'Kafin Hausa',
    'Kazaure',
    'Kiri Kasama',
    'Kiyawa',
    'Kaugama',
    'Maigatari',
    'Malam Madori',
    'Miga',
    'Ringim',
    'Roni',
    'Sule Tankarkar',
    'Taura',
    'Yankwashi',
  ],
  'Kaduna State': [
    'Birnin Gwari',
    'Chikun',
    'Giwa',
    'Igabi',
    'Ikara',
    'Jaba',
    'Jema a',
    'Kachia',
    'Kaduna North',
    'Kaduna South',
    'Kagarko',
    'Kajuru',
    'Kaura',
    'Kauru',
    'Kubau',
    'Kudan',
    'Lere',
    'Makarfi',
    'Sabon Gari',
    'Sanga',
    'Soba',
    'Zangon Kataf',
    'Zaria',
  ],
  'Kano State': [
    'Ajingi',
    'Albasu',
    'Bagwai',
    'Bebeji',
    'Bichi',
    'Bunkure',
    'Dala',
    'Dambatta',
    'Dawakin Kudu',
    'Dawakin Tofa',
    'Doguwa',
    'Fagge',
    'Gabasawa',
    'Garko',
    'Garun Mallam',
    'Gaya',
    'Gezawa',
    'Gwale',
    'Gwarzo',
    'Kabo',
    'Kano Municipal',
    'Karaye',
    'Kibiya',
    'Kiru',
    'Kumbotso',
    'Kunchi',
    'Kura',
    'Madobi',
    'Makoda',
    'Minjibir',
    'Nasarawa',
    'Rano',
    'Rimin Gado',
    'Rogo',
    'Shanono',
    'Sumaila',
    'Takai',
    'Tarauni',
    'Tofa',
    'Tsanyawa',
    'Tudun Wada',
    'Ungogo',
    'Warawa',
    'Wudil',
  ],
  'Katsina State': [
    'Bakori',
    'Batagarawa',
    'Batsari',
    'Baure',
    'Bindawa',
    'Charanchi',
    'Dandume',
    'Danja',
    'Dan Musa',
    'Daura',
    'Dutsi',
    'Dutsin Ma',
    'Faskari',
    'Funtua',
    'Ingawa',
    'Jibia',
    'Kafur',
    'Kaita',
    'Kankara',
    'Kankia',
    'Katsina',
    'Kurfi',
    'Kusada',
    'Mai Adua',
    'Malumfashi',
    'Mani',
    'Mashi',
    'Matazu',
    'Musawa',
    'Rimi',
    'Sabuwa',
    'Safana',
    'Sandamu',
    'Zango',
  ],
  'Kebbi State': [
    'Aleiro',
    'Arewa Dandi',
    'Argungu',
    'Augie',
    'Bagudo',
    'Birnin Kebbi',
    'Bunza',
    'Dandi',
    'Fakai',
    'Gwandu',
    'Jega',
    'Kalgo',
    'Koko Besse',
    'Maiyama',
    'Ngaski',
    'Sakaba',
    'Shanga',
    'Suru',
    'Wasagu Danko',
    'Yauri',
    'Zuru',
  ],
  'Kogi State': [
    'Adavi',
    'Ajaokuta',
    'Ankpa',
    'Bassa',
    'Dekina',
    'Ibaji',
    'Idah',
    'Igalamela Odolu',
    'Ijumu',
    'Kabba Bunu',
    'Kogi',
    'Lokoja',
    'Mopa Muro',
    'Ofu',
    'Ogori Magongo',
    'Okehi',
    'Okene',
    'Olamaboro',
    'Omala',
    'Yagba East',
    'Yagba West',
  ],
  'Kwara State': [
    'Asa',
    'Baruten',
    'Edu',
    'Ekiti',
    'Ifelodun',
    'Ilorin East',
    'Ilorin South',
    'Ilorin West',
    'Irepodun',
    'Isin',
    'Kaiama',
    'Moro',
    'Offa',
    'Oke Ero',
    'Oyun',
    'Pategi',
  ],
  'Lagos State': [
    'Agege',
    'Ajeromi-Ifelodun',
    'Alimosho',
    'Amuwo-Odofin',
    'Apapa',
    'Badagry',
    'Epe',
    'Eti Osa',
    'Ibeju-Lekki',
    'Ifako-Ijaiye',
    'Ikeja',
    'Ikorodu',
    'Kosofe',
    'Lagos Island',
    'Lagos Mainland',
    'Mushin',
    'Ojo',
    'Oshodi-Isolo',
    'Shomolu',
    'Surulere',
  ],
  'Nasarawa State': [
    'Akwanga',
    'Awe',
    'Doma',
    'Karu',
    'Keana',
    'Keffi',
    'Kokona',
    'Lafia',
    'Nasarawa',
    'Nasarawa Egon',
    'Obi',
    'Toto',
    'Wamba',
  ],
  'Niger State': [
    'Agaie',
    'Agwara',
    'Bida',
    'Borgu',
    'Bosso',
    'Chanchaga',
    'Edati',
    'Gbako',
    'Gurara',
    'Katcha',
    'Kontagora',
    'Lapai',
    'Lavun',
    'Magama',
    'Mariga',
    'Mashegu',
    'Mokwa',
    'Moya',
    'Paikoro',
    'Rafi',
    'Rijau',
    'Shiroro',
    'Suleja',
    'Tafa',
    'Wushishi',
  ],
  'Ogun State': [
    'Abeokuta North',
    'Abeokuta South',
    'Ado-Odo Ota',
    'Egbado North',
    'Egbado South',
    'Ewekoro',
    'Ifo',
    'Ijebu East',
    'Ijebu North',
    'Ijebu North East',
    'Ijebu Ode',
    'Ikenne',
    'Imeko Afon',
    'Ipokia',
    'Obafemi Owode',
    'Odeda',
    'Odogbolu',
    'Ogun Waterside',
    'Remo North',
    'Shagamu',
  ],
  'Ondo State': [
    'Akoko North-East',
    'Akoko North-West',
    'Akoko South-West',
    'Akoko South-East',
    'Akure North',
    'Akure South',
    'Ese Odo',
    'Idanre',
    'Ifedore',
    'Ilaje',
    'Ile Oluji-Okeigbo',
    'Irele',
    'Odigbo',
    'Okitipupa',
    'Ondo East',
    'Ondo West',
    'Ose',
    'Owo',
  ],
  'Osun State': [
    'Atakunmosa East',
    'Atakunmosa West',
    'Aiyedaade',
    'Aiyedire',
    'Boluwaduro',
    'Boripe',
    'Ede North',
    'Ede South',
    'Ife Central',
    'Ife East',
    'Ife North',
    'Ife South',
    'Egbedore',
    'Ejigbo',
    'Ifedayo',
    'Ifelodun',
    'Ila',
    'Ilesa East',
    'Ilesa West',
    'Irepodun',
    'Irewole',
    'Isokan',
    'Iwo',
    'Obokun',
    'Odo Otin',
    'Ola Oluwa',
    'Olorunda',
    'Oriade',
    'Orolu',
    'Osogbo',
  ],
  'Oyo State': [
    'Afijio',
    'Akinyele',
    'Atiba',
    'Atisbo',
    'Egbeda',
    'Ibadan North',
    'Ibadan North-East',
    'Ibadan North-West',
    'Ibadan South-East',
    'Ibadan South-West',
    'Ibarapa Central',
    'Ibarapa East',
    'Ibarapa North',
    'Ido',
    'Irepo',
    'Iseyin',
    'Itesiwaju',
    'Iwajowa',
    'Kajola',
    'Lagelu',
    'Ogbomosho North',
    'Ogbomosho South',
    'Ogo Oluwa',
    'Olorunsogo',
    'Oluyole',
    'Ona Ara',
    'Orelope',
    'Ori Ire',
    'Oyo',
    'Oyo East',
    'Saki East',
    'Saki West',
    'Surulere',
  ],
  'Plateau State': [
    'Bokkos',
    'Barkin Ladi',
    'Bassa',
    'Jos East',
    'Jos North',
    'Jos South',
    'Kanam',
    'Kanke',
    'Langtang South',
    'Langtang North',
    'Mangu',
    'Mikang',
    'Pankshin',
    'Qua an Pan',
    'Riyom',
    'Shendam',
    'Wase',
  ],
  'Sokoto State': [
    'Binji',
    'Bodinga',
    'Dange Shuni',
    'Gada',
    'Goronyo',
    'Gudu',
    'Gwadabawa',
    'Illela',
    'Isa',
    'Kebbe',
    'Kware',
    'Rabah',
    'Sabon Birni',
    'Shagari',
    'Silame',
    'Sokoto North',
    'Sokoto South',
    'Tambuwal',
    'Tangaza',
    'Tureta',
    'Wamako',
    'Wurno',
    'Yabo',
  ],
  'Taraba State': [
    'Ardo Kola',
    'Bali',
    'Donga',
    'Gashaka',
    'Gassol',
    'Ibi',
    'Jalingo',
    'Karim Lamido',
    'Kumi',
    'Lau',
    'Sardauna',
    'Takum',
    'Ussa',
    'Wukari',
    'Yorro',
    'Zing',
  ],
  'Yobe State': [
    'Bade',
    'Bursari',
    'Damaturu',
    'Fika',
    'Fune',
    'Geidam',
    'Gujba',
    'Gulani',
    'Jakusko',
    'Karasuwa',
    'Machina',
    'Nangere',
    'Nguru',
    'Potiskum',
    'Tarmuwa',
    'Yunusari',
    'Yusufari',
  ],
  'Zamfara State': [
    'Anka',
    'Bakura',
    'Birnin Magaji Kiyaw',
    'Bukkuyum',
    'Bungudu',
    'Gummi',
    'Gusau',
    'Kaura Namoda',
    'Maradun',
    'Maru',
    'Shinkafi',
    'Talata Mafara',
    'Chafe',
    'Zurmi',
  ],
}

const cities: any = {
  'Abia State': [
    'Aba',
    'Amaigbo',
    'Arochukwu',
    'Bende',
    'Ohafia-Ifigh',
    'Umuahia',
  ],
  'Adamawa State': [
    'Ganye',
    'Gombi',
    'Holma',
    'Jimeta',
    'Madagali',
    'Mayo-Belwa',
    'Mubi',
    'Ngurore',
    'Numan',
    'Toungo',
    'Yola',
  ],
  'Akwa Ibom State': ['Eket', 'Esuk Oron', 'Ikot Ekpene', 'Itu', 'Uyo'],
  'Anambra State': [
    'Agulu',
    'Atani',
    'Awka',
    'Enugu-Ukwu',
    'Igbo-Ukwu',
    'Ihiala',
    'Nkpor',
    'Nnewi',
    'Onitsha',
    'Ozubulu',
    'Uga',
    'Uruobo-Okija',
  ],
  'Bauchi State': [
    'Azare',
    'Bauchi',
    'Boi',
    'Bununu',
    'Darazo',
    'Dass',
    'Dindima',
    'Disina',
    'Gabarin',
    'Gwaram',
    'Kari',
    'Lame',
    'Lere',
    'Madara',
    'Misau',
    'Sade',
    'Yamrat',
    'Yanda Bayo',
    'Yuli',
    'Zadawa',
    'Zalanga',
  ],
  'Bayelsa State': ['Amassoma', 'Twon-Brass', 'Yenagoa'],
  'Benue State': [
    'Aliade',
    'Boju',
    'Igbor',
    'Makurdi',
    'Ochobo',
    'Otukpa',
    'Takum',
    'Ugbokpo',
    'Yandev',
    'Zaki Biam',
  ],
  'Borno State': [
    'Bama',
    'Benisheikh',
    'Biu',
    'Bornu Yassu',
    'Damasak',
    'Damboa',
    'Dikwa',
    'Gamboru',
    'Gwoza',
    'Kukawa',
    'Magumeri',
    'Maiduguri',
    'Marte',
    'Miringa',
    'Monguno',
    'Ngala',
    'Shaffa',
    'Shani',
    'Tokombere',
    'Uba',
    'Wuyo',
    'Yajiwa',
  ],
  'Cross River State': ['Akankpa', 'Calabar', 'Gakem', 'Ikang', 'Ugep'],
  'Delta State': [
    'Abraka',
    'Agbor',
    'Asaba',
    'Bomadi',
    'Burutu',
    'Kwale',
    'Obiaruku',
    'Ogwashi-Uku',
    'Orerokpe',
    'Patani',
    'Sapele',
    'Ughelli',
    'Umunede',
    'Warri',
  ],
  'Ebonyi State': ['Abakaliki', 'Afikpo', 'Effium', 'Ezza-Ohu', 'Isieke'],
  'Edo State': [
    'Agenebode',
    'Auchi',
    'Benin City',
    'Ekpoma',
    'Igarra',
    'Illushi',
    'Siluko',
    'Ubiaja',
    'Uromi',
  ],
  'Ekiti State': [
    'Ado-Ekiti',
    'Aramoko-Ekiti',
    'Efon-Alaaye',
    'Emure-Ekiti',
    'Ifaki',
    'Igbara-Odo',
    'Igede-Ekiti',
    'Ijero-Ekiti',
    'Ikere-Ekiti',
    'Ipoti',
    'Ise-Ekiti',
    'Oke Ila',
    'Omuo-Ekiti',
  ],
  'Enugu State': [
    'Adani',
    'Ake-Eze',
    'Aku',
    'Amagunze',
    'Awgu',
    'Eha Amufu',
    'Enugu',
    'Enugu-Ezike',
    'Ete',
    'Ikem',
    'Mberubu',
    'Nsukka',
    'Obolo-Eke (1)',
    'Opi',
    'Udi',
  ],
  'Federal Capital Territory': ['Abuja', 'Kuje', 'Kwali', 'Madala'],
  'Gombe State': [
    'Akko',
    'Bara',
    'Billiri',
    'Dadiya',
    'Deba',
    'Dukku',
    'Garko',
    'Gombe',
    'Hinna',
    'Kafarati',
    'Kaltungo',
    'Kumo',
    'Nafada',
    'Pindiga',
  ],
  'Imo State': ['Iho', 'Oguta', 'Okigwe', 'Orlu', 'Orodo', 'Owerri'],
  'Jigawa State': [
    'Babura',
    'Birnin Kudu',
    'Birniwa',
    'Dutse',
    'Gagarawa',
    'Gumel',
    'Gwaram',
    'Hadejia',
    'Kafin Hausa',
    'Kazaure',
    'Kiyawa',
    'Mallammaduri',
    'Ringim',
    'Samamiya',
  ],
  'Kaduna State': [
    'Anchau',
    'Burumburum',
    'Dutsen Wai',
    'Hunkuyi',
    'Kachia',
    'Kaduna',
    'Kafanchan',
    'Kagoro',
    'Kajuru',
    'Kujama',
    'Lere',
    'Mando',
    'Saminaka',
    'Soba',
    'Sofo-Birnin-Gwari',
    'Zaria',
  ],
  'Kano State': ['Dan Gora', 'Gaya', 'Kano'],
  'Katsina State': [
    'Danja',
    'Dankama',
    'Daura',
    'Dutsin-Ma',
    'Funtua',
    'Gora',
    'Jibia',
    'Jikamshi',
    'Kankara',
    'Katsina',
    'Mashi',
    'Ruma',
    'Runka',
    'Wagini',
  ],
  'Kebbi State': [
    'Argungu',
    'Bagudo',
    'Bena',
    'Bin Yauri',
    'Birnin Kebbi',
    'Dabai',
    'Dakingari',
    'Gulma',
    'Gwandu',
    'Jega',
    'Kamba',
    'Kangiwa',
    'Kende',
    'Mahuta',
    'Maiyama',
    'Shanga',
    'Wasagu',
    'Zuru',
  ],
  'Kogi State': [
    'Abocho',
    'Adoru',
    'Ankpa',
    'Bugana',
    'Dekina',
    'Egbe',
    'Icheu',
    'Idah',
    'Isanlu-Itedoijowa',
    'Kabba',
    'Koton-Karfe',
    'Lokoja',
    'Ogaminana',
    'Ogurugu',
    'Okene',
  ],
  'Kwara State': [
    'Ajasse Ipo',
    'Bode Saadu',
    'Gwasero',
    'Ilorin',
    'Jebba',
    'Kaiama',
    'Lafiagi',
    'Offa',
    'Okuta',
    'Omu-Aran',
    'Patigi',
    'Suya',
    'Yashikera',
  ],
  'Lagos State': [
    'Apapa',
    'Badagry',
    'Ebute Ikorodu',
    'Ejirin',
    'Epe',
    'Ikeja',
    'Lagos',
    'Lekki',
    'Ikorodu',
    'Ojo',
    'Makoko',
  ],
  'Nasarawa State': ['Buga', 'Doma', 'Keffi', 'Lafia', 'Nasarawa', 'Wamba'],
  'Niger State': [
    'Auna',
    'Babana',
    'Badeggi',
    'Baro',
    'Bokani',
    'Duku',
    'Ibeto',
    'Konkwesso',
    'Kontagora',
    'Kusheriki',
    'Kuta',
    'Lapai',
    'Minna',
    'New Shagunnu',
    'Suleja',
    'Tegina',
    'Ukata',
    'Wawa',
    'Zungeru',
  ],
  'Ogun State': [
    'Abeokuta',
    'Ado Odo',
    'Idi Iroko',
    'Ifo',
    'Ijebu-Ife',
    'Ijebu-Igbo',
    'Ijebu-Ode',
    'Ilaro',
    'Imeko',
    'Iperu',
    'Isara',
    'Owode',
  ],
  'Ondo State': [
    'Agbabu',
    'Akure',
    'Idanre',
    'Ifon',
    'Ilare',
    'Ode',
    'Ondo',
    'Ore',
    'Owo',
  ],
  'Osun State': [
    'Apomu',
    'Ejigbo',
    'Gbongan',
    'Ijebu-Jesa',
    'Ikire',
    'Ikirun',
    'Ila Orangun',
    'Ile-Ife',
    'Ilesa',
    'Ilobu',
    'Inisa',
    'Iwo',
    'Modakeke',
    'Oke Mesi',
    'Olupona',
    'Osogbo',
    'Otan Ayegbaju',
    'Oyan',
  ],
  'Oyo State': [
    'Ago Are',
    'Alapa',
    'Fiditi',
    'Ibadan',
    'Igbeti',
    'Igbo-Ora',
    'Igboho',
    'Kisi',
    'Lalupon',
    'Ogbomoso',
    'Okeho',
    'Orita Eruwa',
    'Oyo',
    'Saki',
  ],
  'Plateau State': [
    'Amper',
    'Bukuru',
    'Dengi',
    'Jos',
    'Kwolla',
    'Langtang',
    'Pankshin',
    'Panyam',
    'Vom',
    'Yelwa',
  ],
  'Sokoto State': [
    'Binji',
    'Dange',
    'Gandi',
    'Goronyo',
    'Gwadabawa',
    'Illela',
    'Rabah',
    'Sokoto',
    'Tambuwal',
    'Wurno',
  ],
  'Taraba State': [
    'Baissa',
    'Beli',
    'Gassol',
    'Gembu',
    'Ibi',
    'Jalingo',
    'Lau',
    'Mutum Biyu',
    'Riti',
    'Wukari',
  ],
  'Yobe State': [
    'Damaturu',
    'Dankalwa',
    'Dapchi',
    'Daura',
    'Fika',
    'Gashua',
    'Geidam',
    'Goniri',
    'Gorgoram',
    'Gujba',
    'Gwio Kura',
    'Kumagunnam',
    'Lajere',
    'Machina',
    'Nguru',
    'Potiskum',
  ],
  'Zamfara State': [
    'Anka',
    'Dan Sadau',
    'Gummi',
    'Gusau',
    'Kaura Namoda',
    'Kwatarkwashi',
    'Maru',
    'Moriki',
    'Sauri',
    'Tsafe',
  ],
  Rivers: [
    'Port Harcourt',
    'Obio-Akpor',
    'Eleme',
    'Oyigbo',
    'Ikwerre',
    'Emohua',
    'Etche',
    'Gokana',
    'Khana',
    'Tai',
    'Ogu–Bolo',
    'Andoni',
    'Bonny',
    'Degema',
    'Asari-Toru',
    'Akuku-Toru',
    'Okrika',
    'Ahoada East',
    'Ahoada West',
    'Omuma',
    'Ikwerre',
    'Ogba–Egbema–Ndoni',
    'Opobo–Nkoro',
    'Ikwerre',
    'Abua–Odual',
    'Okrika',
    'Oyigbo',
    'Tai',
    'Akuku-Toru',
    'Andoni',
    'Khana',
    'Gokana',
    'Eleme',
    'Obio-Akpor',
    'Port Harcourt',
    'Bonny',
    'Degema',
    'Asari-Toru',
    'Opobo–Nkoro',
    'Ikwerre',
    'Ahoada East',
    'Ahoada West',
    'Omuma',
    'Ogba–Egbema–Ndoni',
    'Abua–Odual',
  ],
}

const states: { name: string; state_code: string }[] = [
  { name: 'Abia State', state_code: 'AB' },
  { name: 'Adamawa State', state_code: 'AD' },
  { name: 'Akwa Ibom State', state_code: 'AK' },
  { name: 'Anambra State', state_code: 'AN' },
  { name: 'Bauchi State', state_code: 'BA' },
  { name: 'Bayelsa State', state_code: 'BY' },
  { name: 'Benue State', state_code: 'BE' },
  { name: 'Borno State', state_code: 'BO' },
  { name: 'Cross River State', state_code: 'CR' },
  { name: 'Delta State', state_code: 'DE' },
  { name: 'Ebonyi State', state_code: 'EB' },
  { name: 'Edo State', state_code: 'ED' },
  { name: 'Ekiti State', state_code: 'EK' },
  { name: 'Enugu State', state_code: 'EN' },
  { name: 'Federal Capital Territory', state_code: 'FC' },
  { name: 'Gombe State', state_code: 'GO' },
  { name: 'Imo State', state_code: 'IM' },
  { name: 'Jigawa State', state_code: 'JI' },
  { name: 'Kaduna State', state_code: 'KD' },
  { name: 'Kano State', state_code: 'KN' },
  { name: 'Katsina State', state_code: 'KT' },
  { name: 'Kebbi State', state_code: 'KE' },
  { name: 'Kogi State', state_code: 'KO' },
  { name: 'Kwara State', state_code: 'KW' },
  { name: 'Lagos State', state_code: 'LA' },
  { name: 'Nasarawa State', state_code: 'NA' },
  { name: 'Niger State', state_code: 'NI' },
  { name: 'Ogun State', state_code: 'OG' },
  { name: 'Ondo State', state_code: 'ON' },
  { name: 'Osun State', state_code: 'OS' },
  { name: 'Oyo State', state_code: 'OY' },
  { name: 'Plateau State', state_code: 'PL' },
  { name: 'Sokoto State', state_code: 'SO' },
  { name: 'Taraba State', state_code: 'TA' },
  { name: 'Yobe State', state_code: 'YO' },
  { name: 'Zamfara State', state_code: 'ZA' },
]

const RiverCities = [
  'Abalama',
  'Abonnema',
  'Afam',
  'Ahoada',
  'Andoni',
  'Ataba',
  'Bane',
  'Bonny',
  'Bori',
  'Billie',
  'Bodo',
  'Buguma',
  'Degema Town',
  'Diobu',
  'D-line',
  'Eberi',
  'Elele',
  'Elelenwo',
  'Elekahia',
  'Emohua',
  'Eliozu',
  'Iboloji',
  'Igwuruta',
  'Igbo-Etche',
  'Kula',
  'Mbiama',
  'Mgbuoba',
  'Nkoro',
  'Odiabidi',
  'Okehi',
  'Okobie',
  'Okoloma',
  'Okomoko',
  'Okrika',
  'Omoku',
  'Onne',
  'Ogbunabali',
  'Opobo',
  'Oyorokoto',
  'Oyigbo',
  'Rumuokoro',
  'Rumuola',
  'Rumuigbo',
  'Umuagbai',
  'Umuchitta',
  'Umuru',
  'Usokun-Degema',
  'Unyeada Kingdom',
]

export class LocationController {
  async getStates(req: Request, res: Response) {
    try {
      res.status(200).send({
        message: 'Fetch succesfull',
        data: [...states, { name: 'Rivers' }].sort((a, b) =>
          a.name.localeCompare(b.name),
        ),
      })
    } catch (error: any) {
      res.status(500).send({ message: error.message, data: [] })
    }
  }
  async getCities(req: Request, res: Response) {
    const { state } = req.body
    res
      .status(200)
      .send({ message: `${state} retrieved`, data: [...cities[state]] })
  }
  async getLgas(req: Request, res: Response) {
    const { lga } = req.body
    const ind = lga as unknown as string
    res
      .status(200)
      .send({ message: `Lga in ${lga} retrieved`, data: [...holder[ind]] })
  }
}
